name: ranges
description: Date / Int / Double ranges
version: 3.0.7
#homepage: https://www.example.com
#author: edlman <email@example.com>
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

