name: ac_ranges
description: Date / Int / Double ranges
version: 3.0.11
homepage: https://github.com/anycode/ac_ranges.dart.git
repository: https://github.com/anycode/ac_ranges.dart.git
publish_to: https://pub.anycode.dev

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2

