name: ac_ranges
description: Date / Int / Double ranges
version: 3.0.8
homepage: https://github.com/anycode/ac_ranges.dart.git
repository: https://github.com/anycode/ac_ranges.dart.git
publish_to: https://pub.anycode.dev

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

